# -*- coding: utf-8 -*-
"""My Money Flow: An EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcVh1Tca4YRZmpFtUvEHl7NcbGp1XQqt
"""

# Step 1: Import Libraries & Load Dataset
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv(r"/content/personal_finance_expense_data_2025.csv")

# Display basic info
print(df.shape)
print(df.head())
df.info()

# Step 2: Data Cleaning
print(df.isnull().sum())  # check missing values
df.drop_duplicates(inplace=True)

# Convert date column to datetime
df["Date"] = pd.to_datetime(df["Date"])

# Extract month and day for trends
df["Month_Num"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

df.head()

# Step 3: Exploratory Data Analysis (EDA)
# 3.1 Monthly Expense Trend
Highest_Spending_Month = df.groupby("Month")["Amount "].sum().idxmax()
print(Highest_Spending_Month)

monthly_expense = df.groupby("Month")["Amount "].sum().sort_index()
plt.figure(figsize=(10,5))
sns.barplot(x=monthly_expense.index, y=monthly_expense.values)
plt.title("Total Monthly Expenses (₹)")
plt.xticks(rotation=45)
plt.show()

# 3.2 Category-wise Spending


plt.figure(figsize=(8,5))
sns.barplot(x=df["Category"].value_counts().index,
            y=df.groupby("Category")["Amount "].sum().values)
plt.title("Total Spending by Category")
plt.xticks(rotation=45)
plt.show()

# 3.3 Payment Mode Analysis
Most_Used_Payment_Mode =  df["Payment_Mode"].mode()[0]
print("Most Used Payment Mode:", df["Payment_Mode"].mode()[0])

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Payment_Mode")
plt.title("Transaction Count by Payment Mode")
plt.show()

# 3.4 Daily Spending Distribution
daily_expense = df.groupby("Date")["Amount "].sum()
plt.figure(figsize=(12,5))
plt.plot(daily_expense.index, daily_expense.values)
plt.title("Daily Expense Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Total Expense (₹)")
plt.show()

# Step 4: Compute top 3
print("Top 3 Categories by Spend:\n", df.groupby("Category")["Amount "].sum().sort_values(ascending=False).head(3))

category_spending = df.groupby("Category")["Amount "].sum().sort_values(ascending=False)
top3 = category_spending.head(3)

plt.figure(figsize=(7,5))
sns.barplot(x=top3.index, y=top3.values, palette="mako")

for i, v in enumerate(top3.values):
    plt.text(i, v + 200, f"₹{int(v)}", ha='center', fontweight='bold')

plt.title("🏷️ Top 3 Expense Categories", fontsize=14)
plt.xlabel("Category")
plt.ylabel("Total Expense (₹)")
plt.tight_layout()
plt.show()

# Step 5 : Monthly Trend by Category
pivot = df.pivot_table(index="Month", columns="Category", values="Amount ", aggfunc="sum")
pivot.plot(kind="line", figsize=(12,6), marker="o")
plt.title("Monthly Expense Trend by Category")
plt.ylabel("Amount (₹)")
plt.grid(True)
plt.show()

# Step 6 : Category share (Pie chart)
df.groupby("Category")["Amount "].sum().plot.pie(autopct="%1.1f%%", figsize=(6,6))
plt.title("Category-wise Expense Share")
plt.ylabel("")
plt.show()

# Step 7: Summary
# ------------------------------------------------------------

print("\n🧩 FINAL SUMMARY – Personal Finance EDA")

print(f"""
🔹 Objective:
   Analyze personal finance data to understand monthly spending trends,
   category-wise distribution, and payment behavior.

🔹 Key Findings:
   - Highest Spending Month: {Highest_Spending_Month}
   - Most Used Payment Mode: {Most_Used_Payment_Mode}
   - Top 3 Spending Categories: {top3}

💡 Insights:
   - Spending peaks in certain months due to lifestyle or seasonal factors.
   - Digital payments dominate overall transactions.
   - Essentials like groceries, rent, or utilities are top expense areas.

✅ Conclusion:
   Tracking expenses monthly enables better budget control and savings planning.
   This EDA can be extended with predictive analysis or Power BI dashboards.
""")

